### PR TITLE
GAP: improve filename format

### PR DESCRIPTION
**Pull request by vladh**
Previously, GAP files were named:

> St. Germain l'Auxerrois - Claude Monet.jpg

This PR changes the format to:

> Monet, Claude; St. Germain l'Auxerrois; 1867.jpg

This makes the files easy to group together when downloading multiple different files, includes the year which is important for my use-case, and is overall a nicer format in my opinion.

Notes:
* I currently assume the author of the painting has at least two space-separated names. If the author was e.g. "Socrates", the fallback filename would be used. I will continue testing and will send an additional PR if I encounter this case.
* I am getting the data from the HTML and not from the JSON found within the HTML. I don't think this is actually worse than the previous strategy of using the JSON — they are both liable to change, and the JSON does not reliably include the full information such as the author name.

### CODE REVIEW

**Comment by lovasoa** [comment]
This new parsing seems more likely to break than the old one. Can you add a fallback to the old one if your regex doesn't match ? and extract the logic to a separate function?

**Comment by vladh** [comment]
@lovasoa Makes sense, done!

**Comment by vladh** [comment]
@lovasoa Would you like to see any changes on this?

**Comment by lovasoa** [comment]
No, I'm ok to merge once the tests pass

**Comment by vladh** [comment]
D'oh, sorry, will fix very soon.

**Comment by vladh** [comment]
@lovasoa Should be okay now, a test still seems to fail but I think it's unrelated? It also passes locally which I find confusing.

**Comment by lovasoa** [comment]
Do you have the latest release of rust?

**Comment by vladh** [comment]
I can check, but just to confirm, would you like me to fix the failing test that is unrelated to my code? I could also do that in another PR.

**Pull request merged**
